import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";
import MuiThemeProvider from "./theme";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <MuiThemeProvider>
            <Header />
            {children}
            <Footer />
            </MuiThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
